apm:
  enabled: false
  service_name: "Isac"
  otel_exporter_otlp_endpoint: "0.0.0.0:4317"
  insecure: true

postgres:
  dsn: "host=47.120.68.13 user=ccc password=ccc123 dbname=jumpfrog port=5432 sslmode=disable"

redis:
  addr: "47.120.68.13:6379"
  password: "ccc123"

http:
  addr: ":8080"

cron:
  enabled: true
  spec: "@every 10s" 

