// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"framework/apm"
	"framework/config"
	"framework/log"
	"framework/server/http"
)

// Injectors from wire.go:

func createApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := log.NewLogger(configConfig)
	echo := http.NewEcho(logger, configConfig)
	httpServer := &http.HTTPServer{
		Echo: echo,
	}
	tracer, err := apm.NewTracer(configConfig)
	if err != nil {
		return nil, err
	}
	app := &App{
		HTTPServer: httpServer,
		Config:     configConfig,
		Tracer:     tracer,
	}
	return app, nil
}

// wire.go:

type App struct {
	HTTPServer *http.HTTPServer
	Config     *config.Config
	Tracer     *apm.Tracer
}
