// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"framework/config"
	"framework/cronjob"
	"framework/db/pg"
	"framework/repo"
)

// Injectors from wire.go:

func createApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := pg.NewDB()
	if err != nil {
		return nil, err
	}
	gormDB := pg.ProvideGormDB(db)
	userRepo := repo.NewUserRepo(gormDB)
	helloWorldJob := cronjob.NewHelloWorldJob(userRepo)
	app := &App{
		Config:        configConfig,
		HelloWorldJob: helloWorldJob,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config        *config.Config
	HelloWorldJob *cronjob.HelloWorldJob
}
